server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** # 路由到搜索的微服务  //这个地方是ctrl+d 复制上面的报错,查了很久教训
    user-service: /user/**
    auth-service: /auth/** # 授权中心微服务
